//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyReads.Models
{
    using MyReads.Classes;
    using System;
    using System.Collections.Generic;
    public partial class UserBooks
    {
        public int UB_UserID { get; set; }
        public int UB_BookID { get; set; }
        public Nullable<double> UB_Rating { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
